### ISSUE TITLE
Node not recognizing ReJSON commands

### ISSUE THREAD

**Issue by latvape** [stockholmux/node_redis-rejson#7]
Hi, 
I have been testing redis and redis-rejson with node.js and I cannot get node to work even with the basic examples provided in redis-rejson readme.md. When using the readmes example Node gives an error: 
`
/home/petrilk/Documents/git/dashboard/server/testing_redis.js:10
  if (err) { throw err; }
ReplyError: ERR unknown command 'json.set'
    at parseError (/home/petrilk/Documents/git/dashboard/server/node_modules/redis-parser
/lib/parser.js:193:12)
    at parseType (/home/petrilk/Documents/git/dashboard/server/node_modules/redis-parser/lib/parser.js:303:14)`

So as I understand the redis-rejson connection works as the error says `json.set` and I have written `client.json_set` in the code as instructed. 

Does anyone know where the problem might be, in redis, redis-Rejson, or something else?

**Comment by stockholmux** [comment]
`ERR unknown command 'json.set` is coming from Redis itself (`client.json_set` is correct node.js syntax, it translates to `json.set`, the Redis command). 

You have to (install the rejson redis module)[https://oss.redislabs.com/redisjson/] (now renamed to RedisJson) in Redis before you can use this Node.js module. 

I'm going to close this since it's not a problem with this module, but feel free to post questions.
